name: lua-esp
on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: get esp-idf
        run: |
          pwd
          cd ~
          mkdir -p ~/esp
          cd ~/esp
          git clone --recursive https://github.com/espressif/esp-idf.git
          cd ~/esp/esp-idf
          git checkout v4.3.1
          ./install.sh
      - name: test idf
        run: |
          cd ~/esp/esp-idf
          source export.sh
          idf.py --version
      - name: test usr
        run: |
          cd ~
          ls
