name: lua-esp
on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: get esp-idf
        run: |
          cd ~
          mkdir -p ~/esp
          cd ~/esp
          git clone --recursive https://github.com/espressif/esp-idf.git
          git checkout v4.3.1
          cd ~/esp/esp-idf
          ./install.sh
      - name: test idf
        run: |
          . ~/esp/esp-idf/export.sh
          idf.py --version
