name: lua-esp
on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: pwd
        run: |
          pwd
          pip3 install --upgrade pip
      - name: get esp-idf
        run: |
          mkdir -p ~/esp
          cd ~/esp
          git clone -b v4.3.1 --recursive https://github.com/espressif/esp-idf.git
          cd ~/esp/esp-idf
          ./install.sh
      - name: build c3
        run: |
          cd ~/esp/esp-idf
          source export.sh
          idf.py --version
          cd ~
          git clone https://gitee.com/dreamcmi/LuatOS-ESP32
          cd LuatOS-ESP32
          idf.py set-target esp32c3
          idf.py build
          cd build/
          ls