name: lua-esp
on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: get brach
        run: git branch -a
      # - name: clone lua
      #   run: git clone https://gitee.com/openLuat/LuatOS
      # - name: rm repo
      #   run: rm -rf LuatOS/
      - name: show dir
        run: |
          ls
          ls demo/
          echo demo/main.lua